In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch

<h2>Tensors</h2>
<a href="https://github.com/jonkrohn/ML-foundations/blob/master/notebooks/1-intro-to-linear-algebra.ipynb">ML-foundations</a>

### Scalars in PyTorch

* PyTorch tensors are designed 'feel' and behave like NumPy arrays
* The advantage of PyTorch tensors relative to NumPy arrays is that they easily be used for operations on GPU (see [here](https://pytorch.org/tutorials/beginner/examples_tensor/two_layer_net_tensor.html) for example) 
* Documentation on PyTorch tensors, including available data types, is [here](https://pytorch.org/docs/stable/tensors.html)

In [3]:
x_pt = torch.tensor(25) # type specification optional, e.g.: dtype=torch.float16
x_pt

tensor(25)

In [4]:
x_pt.shape

torch.Size([])

### Vectors (Rank 1 Tensors) in NumPy

In [5]:
x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
x

array([25,  2,  5])

In [6]:
len(x)

3

In [7]:
x.shape

(3,)

In [8]:
type(x)

numpy.ndarray

In [9]:
x[0] # zero-indexed

25

In [10]:
type(x[0])

numpy.int64

### Vector Transposition

In [11]:
# Transposing a regular 1-D array has no effect...
x_t = x.T
x_t

array([25,  2,  5])

In [12]:
x_t.shape

(3,)

In [13]:
# ...but it does we use nested "matrix-style" brackets: 
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [14]:
y.shape

(1, 3)

In [15]:
# ...but can transpose a matrix with a dimension of length 1, which is mathematically equivalent: 
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [16]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [17]:
# Column vector can be transposed back to original row vector: 
y_t.T 

array([[25,  2,  5]])

In [18]:
y_t.T.shape

(1, 3)

### Zero Vectors

Have no effect if added to another vector

In [19]:
z = np.zeros(3) 
z

array([0., 0., 0.])

### Vectors in PyTorch and TensorFlow

In [20]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [21]:
# we'll cover tensor multiplication more soon but to prove point quickly: 

# 4x1 . 4x1
# 1x4 * 4x1
np.dot(x, x)

654

### Matrices (Rank 2 Tensors) in NumPy

In [22]:
# Use array() with nested brackets: 
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [23]:
X.shape

(3, 2)

In [24]:
X.size

6

In [25]:
# Select left column of matrix X (zero-indexed)
X[:,0]

array([25,  5,  3])

In [71]:
# Select middle row of matrix X: 
X[1,:]

array([ 5, 26])

In [41]:
# Another slicing-by-index example:
X = np.array([[25, 2], [5, 26], [3, 7]])
print(X)
# X[rows, cols]
print(X[0:2, 0:2])

[[25  2]
 [ 5 26]
 [ 3  7]]
[[25  2]
 [ 5 26]]


### Matrices in PyTorch

In [73]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [74]:
X_pt.shape # more pythonic

torch.Size([3, 2])

In [75]:
X_pt[1,:]

tensor([ 5, 26])

<h3>Higher-Rank Tensors</h3>

As an example, rank 4 tensors are common for images, where each dimension corresponds to: 

1. Number of images in training batch, e.g., 32
2. Image height in pixels, e.g., 28 for [MNIST digits](http://yann.lecun.com/exdb/mnist/)
3. Image width in pixels, e.g., 28
4. Number of color channels, e.g., 3 for full-color images (RGB)

In [76]:
images_pt = torch.zeros([32, 28, 28, 3])

**Return to slides here.**

<h3>Segment 2: Common Tensor Operations</h3>

### Tensor Transposition

In [77]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [78]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [79]:
X_pt.T 

tensor([[25,  5,  3],
        [ 2, 26,  7]])

### Basic Arithmetical Properties

Adding or multiplying with scalar applies operation to all elements and tensor shape is retained: 

In [29]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [30]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [31]:
X+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [34]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [36]:
A = X+2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [37]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [38]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

### Reduction

Calculating the sum across all elements of a tensor is a common operation. For example: 

* For vector ***x*** of length *n*, we calculate $\sum_{i=1}^{n} x_i$
* For matrix ***X*** with *m* by *n* dimensions, we calculate $\sum_{i=1}^{m} \sum_{j=1}^{n} X_{i,j}$

In [ ]:
X

In [ ]:
X.sum()

In [ ]:
torch.sum(X_pt)

In [ ]:
# Can also be done along one specific axis alone, e.g.:
X.sum(axis=0) # summing over all cols

In [ ]:
X.sum(axis=1) # summing over all rows
# https://numpy.org/doc/stable/reference/generated/numpy.sum.html

In [ ]:
torch.sum(X_pt, 0)

Many other operations can be applied with reduction along all or a selection of axes, e.g.:

* maximum
* minimum
* mean
* product

They're fairly straightforward and used less often than summation, so you're welcome to look them up in library docs if you ever need them.

### The Dot Product

If we have two vectors (say, ***x*** and ***y***) with the same length *n*, we can calculate the dot product between them. This is annotated several different ways, including the following: 

* $x \cdot y$
* $x^Ty$
* $\langle x,y \rangle$

Regardless which notation you use (I prefer the first), the calculation is the same; we calculate products in an element-wise fashion and then sum reductively across the products to a scalar value. That is, $x \cdot y = \sum_{i=1}^{n} x_i y_i$

The dot product is ubiquitous in deep learning: It is performed at every artificial neuron in a deep neural network, which may be made up of millions (or orders of magnitude more) of these neurons.

In [ ]:
x

In [ ]:
y = np.array([0, 1, 2])
y

In [ ]:
25*0 + 2*1 + 5*2

In [ ]:
np.dot(x, y)

In [ ]:
x_pt

In [ ]:
y_pt = torch.tensor([0, 1, 2])
y_pt

In [ ]:
np.dot(x_pt, y_pt)

In [ ]:
torch.dot(torch.tensor([25, 2, 5.]), torch.tensor([0, 1, 2.]))

### Matrix Multiplication (with a Vector)

In [71]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [72]:
# Vector
b = np.array([1, 2])
b

array([1, 2])

In [73]:
# 1 x 2
c = np.array([[1, 2]])
c.shape

(1, 2)

In [74]:
A.shape

(3, 2)

In [75]:
b.shape

(2,)

In [76]:
np.dot(A, b) # even though technically dot products are between vectors only

array([11, 17, 23])

In [77]:
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [78]:
b_pt = torch.tensor([1, 2])
b_pt

tensor([1, 2])

In [48]:
torch.matmul(A_pt, b_pt) # like np.dot(), automatically infers dims in order to perform dot product, matvec, or matrix multiplication

tensor([11, 17, 23])

### Matrix Multiplication (with Two Matrices)

In [49]:
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
B = np.array([[1, 9], [2, 0]])
B

In [ ]:
np.dot(A, B)

Note that matrix multiplication is not "commutative" (i.e., $AB \neq BA$) so uncommenting the following line will throw a size mismatch error:

In [ ]:
# np.dot(B, A)

In [ ]:
B_pt = torch.from_numpy(B)
B_pt

In [ ]:
# another neat way to create the same tensor with transposition: 
B_pt = torch.tensor([[1, 2], [9, 0]]).T
B_pt

### Symmetric Matrices

In [ ]:
X_sym = np.array([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
X_sym

In [ ]:
X_sym.T

In [ ]:
X_sym.T == X_sym

**Return to slides here.**

### Identity Matrices

In [ ]:
I = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

In [ ]:
x_pt = torch.tensor([25, 2, 5])
x_pt

In [ ]:
torch.matmul(I, x_pt)

### BONUS: Matrix Inversion

In [ ]:
X = np.array([[4, 2], [-5, -3]])
X

In [ ]:
Xinv = np.linalg.inv(X)
Xinv

In [ ]:
torch.inverse(torch.tensor([[4, 2], [-5, -3.]])) # float type